# Generated by Django 3.1.7 on 2021-04-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_name', models.IntegerField()),
                ('extra_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('treatment', models.CharField(max_length=500)),
                ('hospitalized_on', models.DateTimeField(auto_now_add=True)),
                ('is_discharge', models.BooleanField(default=False)),
                ('discharged_on', models.DateTimeField(blank=True, null=True)),
                ('bill', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_info', models.TextField()),
                ('bed', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.bed')),
            ],
        ),
    ]
