# Generated by Django 3.1.7 on 2021-04-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20210409_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
