# Generated by Django 3.1.7 on 2021-04-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_bed_in_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='in_use',
        ),
    ]
