# Generated by Django 3.1.7 on 2021-04-07 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cloths', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloths.cloths')),
            ],
        ),
        migrations.CreateModel(
            name='Inward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cloths', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloths.cloths')),
            ],
        ),
    ]
